### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ArtemT** [xiaq/compl#1]
Hello! When I'm trying to autocomplete go command it throws an exception:
```
Exception: Compilation error: variable $&compl not found
/home/user/.elvish/lib/github.com/xiaq/compl/go.elv, line 278: edit:arg-completer[go] = $&compl
/home/user/.elvish/rc.elv, line 26: use github.com/xiaq/compl/go
```
I'm using Debian stable, my `elvish` binary is compiled from source.

I started to learn Elvish only yesterday and I liked it, but this code really puzzles me. I cannot find any information about this syntax: `'&name' = [ 'a' 'b' 'c' ]` and then `variable = $&name`. Dear @zzamboni was so kind providing his code with detailed explanations, it helps a lot. Could you please help me to understand this syntax?

**Comment by zzamboni** [comment]
I think @xiaq's code might be out of date - `$&compl` is the old way of referring to functions, it should now be `$compl~`. Try changing that in your local copy and see if it works.
